import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { compareReceivableTiming, reverseBreakpoint, MONTHLY_REVERSE_LIMITS } from '../web/src/monthlyEvidence.js';

// Expected financial delta from separately calculated engine outputs;
// no forecast is generated by this display helper.
const delayed = { scenario: {
  inputs: { receivable_delay_days: 14 }, stressed_min_cash: 1423620,
  stressed_end_cash: 1443609.7476387764,
  trajectory: [{period:1, stressed_cash:1400000, receivable_timing_adjustment:-19990},
    {period:2, stressed_cash:1420000, receivable_timing_adjustment:0},
    {period:3, stressed_cash:1443609.7476387764, receivable_timing_adjustment:0}]
}};
const noDelay = { scenario: {
  inputs: { receivable_delay_days: 0 }, stressed_min_cash: 1443610,
  stressed_end_cash: 1443609.7476387764,
  trajectory: [{period:1, stressed_cash:1419990},
    {period:2, stressed_cash:1420000},
    {period:3, stressed_cash:1443609.7476387764}]
}};
const difference = compareReceivableTiming(delayed, noDelay);
assert.equal(difference.minimumCashDifference, -19990);
assert.equal(difference.endCashDifference, 0);
assert.equal(difference.trajectory[0].cashDifference, -19990);
assert.equal(compareReceivableTiming({}, noDelay), null);
assert.equal(reverseBreakpoint(null, 30, '%'), 'Not reached up to 30%');
assert.equal(reverseBreakpoint(null, 90, 'days'), 'Not reached up to 90 days');
assert.equal(reverseBreakpoint(null, 30, '%', true), 'Already below target');
assert.equal(reverseBreakpoint(0.1, 30, '%'), '10.0%');
assert.equal(reverseBreakpoint(0, 90, 'days'), '0 days');
assert.deepEqual(MONTHLY_REVERSE_LIMITS, { revenuePct:30, costPct:30, delayDays:90 });
console.log('Monthly financial-display helper: 10 assertions passed');

const read = file => readFileSync(new URL(file, import.meta.url), 'utf8');
const monthly = read('../web/src/RestoredWorkspaces.jsx');
const importUI = read('../web/src/CustomerAdvancedImport.jsx');
const app = read('../web/src/App.jsx');
assert.ok(monthly.includes('receivable_delay_days: 0'), 'No-delay control API scenario missing');
assert.ok(monthly.includes('compareReceivableTiming(stress, timingReference)'), 'Verified comparison not used');
assert.ok(monthly.includes('Contribution at combined peak-gap month'), 'Decomposition scope not labelled');
assert.ok(monthly.includes('Only runtime-reported calls are shown'), 'Monthly AI provenance not qualified');
assert.ok(importUI.includes('evidenceConfirmed') && importUI.includes('disabled={busy || !importReady}'), 'Mapping import not guarded');
assert.ok(importUI.includes('<details className="mapping-preview" open>'), 'Data preview not visible');
assert.ok(app.includes('disabled={importBusy || !file || !policyValid}'), 'Template import guard missing');
assert.ok(app.includes('Company Data Onboarding'), 'Company onboarding header not clarified');
console.log('React workflow contract: 8 assertions passed');
